### ISSUE TITLE
Fails on v5

### ISSUE THREAD

**Issue by ofirgalcon** [poundbangbash/ssd_service_program#2]
Anyone else using this module with v5? For me it fails on the client and the server just displays:

Fatal error: Uncaught Exception: Cannot load model: department_model in /v5/app/helpers/site_helper.php:168 Stack trace: #0 [internal function]: munkireport_autoload('department_mode...') #1 /v5/local/custom-modules/ssd_service_program/views/ssd_service_program_listing.php(7): spl_autoload_call('department_mode...') #2 /v5/system/kissmvc_core.php(292): include('/v5...') #3 /v5/app/controllers/show.php(55): KISS_View->view('ssd_service_pro...', Array, '/v5...') #4 /v5/system/kissmvc_core.php(84): munkireport\controller\show->listing('ssd_service_pro...', 'ssd_service_pro...') #5 /v5/system/kissmvc.php(17): KISS_Engine->__construct(Array, 'show', 'index', 'AUTO') #6 /v5/bootstrap/app.php(121): Engine->__construct(Array, 'show', 'index', 'AUTO') #7 /v5/public/index.php(7): require_once('/v5... in /v5/app/helpers/site_helper.php on line 168

**Comment by poundbangbash** [comment]
There was a commit to remove references to the department model that was accidentally included from an internal version.  Are you running the latest code for the module?
https://github.com/poundbangbash/ssd_service_program/commit/b6e58e847ab3a95dca78bba5d1f2485e26cfb584

**Comment by ofirgalcon** [comment]
That fixed it, I should have checked! Thanks.
